"""
Resend email sending service.

Resend is the primary provider for cold outreach because:
- Modern IP infrastructure with strong deliverability for cold email.
- Clean REST API with native webhook support for tracking events.
- Open/click tracking via pixel and link wrapping (enable in the Resend
  dashboard under Settings → Email Tracking).

Docs: https://resend.com/docs/api-reference/emails/send-email
"""

from __future__ import annotations

import base64
import logging
from typing import Any

import aiohttp

from core.config import settings
from services.email_attachment import EmailAttachment

logger = logging.getLogger(__name__)

_RESEND_SEND_URL: str = "https://api.resend.com/emails"


class ResendService:
    """Send transactional / cold-outreach emails via the Resend HTTP API."""

    async def send_email(
        self,
        from_email: str,
        from_name: str,
        to_email: str,
        subject: str,
        html_body: str,
        *,
        to_name: str | None = None,
        text_body: str | None = None,
        custom_id: str | None = None,
        tags: list[dict[str, str]] | None = None,
        api_key_override: str | None = None,
        extra_headers: dict[str, str] | None = None,
        bcc: list[str] | None = None,
        attachments: list[EmailAttachment] | None = None,
    ) -> dict[str, Any]:
        """
        Send a single email via Resend.

        The ``custom_id`` is stored as a ``email_log_id`` tag so that incoming
        webhook events can be correlated back to the correct ``EmailLog`` row
        without scanning ``provider_message_id``.

        Args:
            from_email:       Sender address (must be on a Resend-verified domain).
            from_name:        Display name shown to the recipient.
            to_email:         Recipient email address.
            subject:          Email subject line.
            html_body:        HTML content of the email.
            to_name:          Recipient display name (optional).
            text_body:        Plain-text fallback.  Auto-generated by Resend if omitted.
            custom_id:        Stored as an ``email_log_id`` tag for webhook correlation.
            tags:             Additional Resend tags.
            api_key_override: Use this API key instead of the one in settings.
                              Useful when a per-user key is stored in ``resend_config``.
            extra_headers:    Custom SMTP headers forwarded to Resend (e.g.
                              ``List-Unsubscribe`` / ``List-Unsubscribe-Post``).

        Returns:
            Dict with keys ``message_id`` (str) and ``provider`` (str).

        Raises:
            RuntimeError: When no API key is available.
            RuntimeError: When Resend returns a non-2xx HTTP status.
        """
        api_key: str = api_key_override or getattr(settings, "resend_api_key", "")
        if not api_key:
            raise RuntimeError("RESEND_API_KEY is not configured")

        from_field: str = f"{from_name} <{from_email}>" if from_name else from_email
        to_field: str = f"{to_name} <{to_email}>" if to_name else to_email

        payload: dict[str, Any] = {
            "from": from_field,
            "to": [to_field],
            "subject": subject,
            "html": html_body,
        }
        if text_body:
            payload["text"] = text_body
        if extra_headers:
            payload["headers"] = extra_headers
        if bcc:
            payload["bcc"] = bcc
        if attachments:
            payload["attachments"] = [
                {"filename": attachment.filename, "content": base64.b64encode(attachment.content).decode()}
                for attachment in attachments
            ]

        # Build the tags list — always include email_log_id for webhook lookup.
        all_tags: list[dict[str, str]] = []
        if custom_id:
            all_tags.append({"name": "email_log_id", "value": custom_id})
        if tags:
            all_tags.extend(tags)
        if all_tags:
            payload["tags"] = all_tags

        async with (
            aiohttp.ClientSession() as session,
            session.post(
                _RESEND_SEND_URL,
                json=payload,
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                },
                timeout=aiohttp.ClientTimeout(total=30),
            ) as resp,
        ):
            body: dict[str, Any] = await resp.json()
            if resp.status not in (200, 201):
                error_msg: str = body.get("message") or body.get("error") or str(body)
                raise RuntimeError(f"Resend API error {resp.status}: {error_msg}")

            message_id: str = body.get("id", "")
            logger.info("[Resend] Sent to %s — id=%s", to_email, message_id)
            return {"message_id": message_id, "provider": "resend"}
